version: '3.8'
services:
  db:
    container_name: db_container
    image: postgres:latest
    env_file:
      - .env
    ports: 
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgres/data
volumes:
  db_data: